### PR TITLE
add new (paid) synthesizer book

### PR DESCRIPTION
**Pull request by hollance**
Hi, I've added a link to my new book. Feel free to tweak the description! :smiley:

### CODE REVIEW

**Comment by BillyDM** [comment]
Interesting. Although I don't normally add resources to this repository unless someone has vouched that it has actually helped them.

I'll keep this PR open until I get 3rd-party validation for this book.

From what I glean it's a book about JUCE, voice handling logic, oscillators, envelopes, and LFOs? I see one chapter on filters, although that doesn't exactly make a "fully-featured synth" IMO, and I imagine it doesn't go into much detail into how filter and other FX DSP actually works considering it's a math-light book (although I could be wrong, this is just what I could glean from the sample book). I would tweak the description to better represent what this book is.

Still, this does seem to have potential to help beginners. I just want some validation first, especially since it's a paid resource.

**Comment by hollance** [comment]
Fair enough, I think that is very reasonable.

If you want to check out the synth that is being built in the book, the full source code is available here: https://github.com/hollance/synth-plugin-book

**Comment by BillyDM** [comment]
Ah sorry, I forgot about this. I see that this book is now officially endorsed by The Audio Programmer, so it seems legit.

Since there were merge conflicts, I went ahead and added the entry myself, and I updated it to use the correct link.

Anyway, thanks for writing this book!

**Comment by BillyDM** [comment]
83eeb4d

**Comment by hollance** [comment]
Thanks for merging! 😄

**Pull request closed without merging**
