### PR TITLE
max, pd and hvcc

### PR DESCRIPTION
**Pull request by dromer**
Not sure if it makes sense to add here.

### CODE REVIEW

**Comment by BillyDM** [comment]
Hmm, yeah, it's more of a compiler than a plugin development framework. Perhaps it can go in the Low Level Programming Languages section.

**Comment by dromer** [comment]
Well, it's not a `Low Level Programming Language` and since its main interface is currently through Pure Data, which is more a `High Level Programming Language`.

It's really a combination of transpiler and framework that can be used to make a variety of audio plugins.

**Comment by dromer** [comment]
I now notice the `DSP Playgrounds` section, where Pure Data should surely be placed at least.

**Comment by BillyDM** [comment]
Oh yeah, forgot about this PR. I'll just go ahead and merge it.

**Pull request merged**
